event entity @e[family=collectable] minecraft:despawn
summon meraki:rock
summon meraki:twig
summon meraki:seashells
summon meraki:rock
summon meraki:twig
summon meraki:seashells
summon meraki:rock
summon meraki:twig
summon meraki:seashells
summon meraki:rock
summon meraki:twig
summon meraki:seashells
summon meraki:rock
summon meraki:twig
summon meraki:seashells
summon meraki:rock
summon meraki:twig
summon meraki:seashells
summon meraki:rock
summon meraki:twig
summon meraki:seashells
summon meraki:rock
summon meraki:twig
summon meraki:seashells
summon meraki:rock
summon meraki:twig
summon meraki:seashells
summon meraki:rock
summon meraki:twig
summon meraki:seashells
summon meraki:rock
summon meraki:twig
summon meraki:seashells
summon meraki:rock
summon meraki:twig
summon meraki:seashells
summon meraki:rock
summon meraki:twig
summon meraki:seashells
summon meraki:rock
summon meraki:twig
summon meraki:seashells
summon meraki:rock
summon meraki:twig
summon meraki:seashells
summon meraki:rock
summon meraki:twig
summon meraki:seashells
summon meraki:rock
summon meraki:twig
summon meraki:seashells
summon meraki:rock
summon meraki:twig
summon meraki:seashells
summon meraki:rock
summon meraki:twig
summon meraki:seashells
summon meraki:rock
summon meraki:twig
summon meraki:seashells
spreadplayers 2135 -154 1 200 @e[family=collectable]